package com.roomer.app.domain;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

/**
 * Class holding data for Account
 * @author milosz.marzec
 */
@JsonIgnoreProperties({"hibernateLazyInitializer"})
@ToString
@NoArgsConstructor
@Setter
@Getter
@Entity
@Table(name = "account_table")
public class Account {
    /**
     * Unique identifier of the Account.
     * Value is generated by the sequence inside the database. (Initial value = 1, Allocation size = 50)
     */
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
    private long id;

    /**
     * Email associated with the account
     */
    @Column
    private String email;

    /**
     * Password associated with the account
     */
    @Column
    private String password;

    /**
     * User associated with the account
     * It is unidirectional relationship (user entity does not know about the account entity [it is not needed for now])
     */
    @OneToOne(cascade=CascadeType.ALL)
    @JoinColumn(name = "user_id", referencedColumnName = "id")
    private User user;
}
