package com.roomer.app.domain;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

import java.util.Date;


/**
 * Class holding data for Room announcements
 * @author milosz.marzec
 */
@ToString
@NoArgsConstructor
@Setter
@Getter
@Entity
@Table(name = "room_table")
public class Room {
    /**
     * Unique identifier of the Room.
     * Value is generated by the sequence inside the database. (Initial value = 1, Allocation size = 50)
     */
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
    private long id;

    /**
     * Description of the room announcement
     */
    @Column
    private String description;

    /**
     * Data for the person landing the room
     */
    // in the end it should be the Account entity linked here
    @Column
    private String landLord;

    /**
     * Room price
     */
    @Column
    private double price;

    /**
     * Announcement creation date
     */
    @Column
    @Temporal(TemporalType.DATE)
    private Date creationDate;

    /**
     * Room pictures (they should be stored in S3 or something similar)
     */
    @Column
    private String pictureURL;

    @PrePersist
    public void onCreate() {
        this.creationDate = new Date();
    }



}
